# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Root project
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  
  # Main plugin module
  - package-ecosystem: "maven"
    directory: "/play2-maven-plugin"
    schedule:
      interval: "daily"
  
  # Provider API
  - package-ecosystem: "maven"
    directory: "/play2-provider-api"
    schedule:
      interval: "daily"
  
  # Current Play provider (Play 3.0)
  - package-ecosystem: "maven"
    directory: "/play2-providers/play2-provider-play30"
    schedule:
      interval: "daily"
  
  # Source position mappers
  - package-ecosystem: "maven"
    directory: "/play2-source-position-mappers"
    schedule:
      interval: "daily"
  
  # Source watcher API
  - package-ecosystem: "maven"
    directory: "/play2-source-watcher-api"
    schedule:
      interval: "daily"
  
  # Source watchers
  - package-ecosystem: "maven"
    directory: "/play2-source-watchers"
    schedule:
      interval: "daily"
  
  # Legacy Play providers (2.3-2.8) are intentionally excluded
  # These modules must remain compatible with their respective legacy Play versions
