# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      # Ignore dependency updates for old Play framework versions (2.3-2.8)
      # These are maintained for compatibility with legacy applications
      - dependency-name: "play2-providers/play2-provider-play23/*"
      - dependency-name: "play2-providers/play2-provider-play24/*"
      - dependency-name: "play2-providers/play2-provider-play25/*"
      - dependency-name: "play2-providers/play2-provider-play26/*"
      - dependency-name: "play2-providers/play2-provider-play27/*"
      - dependency-name: "play2-providers/play2-provider-play28/*"
